version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(deps):"
