name: Tests

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test

      - name: Run test coverage
        run: npm run test:coverage

      - name: Generate coverage report
        id: coverage
        run: |
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          node -e 'const fs = require("fs"); const coverage = JSON.parse(fs.readFileSync("./coverage/coverage-summary.json")); const total = coverage.total; let table = "### Test Coverage Report\n\n| Category | Percentage | Covered/Total |\n|----------|------------|---------------|\n"; for (const type of ["lines", "statements", "functions", "branches"]) { table += `| ${type.charAt(0).toUpperCase() + type.slice(1)} | ${total[type].pct.toFixed(2)}% | ${total[type].covered}/${total[type].total} |\n`; } console.log(table);' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const coverageSummary = `${{ steps.coverage.outputs.summary }}`;
            
            // Add a fallback in case the summary is still empty
            const body = coverageSummary || '### Test Coverage Report\n\nNo coverage data available.';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

